---
title: "UNFINISHED BART DATA"
author: "Jason Chhay"
date: "3/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readr)
library(ggplot2)
library(reshape2)
bart2011 <- read_csv("date-hour-soo-dest-2011.csv.gz")
names(bart2011) <- c("Day", "Hour", "Origin_Station", "Destination_Station", "Trip_Count")
origin <- bart2011 %>% group_by(Origin_Station) %>% count(Origin_Station) %>% arrange(Origin_Station)
destination <- bart2011 %>% group_by(Destination_Station) %>% count(Destination_Station) %>% arrange(Destination_Station)
names(destination) <- c("Origin_Station", "n")
newBart <- rbind(origin, destination)
newBart$ID <- c(rep("Origin", 44), rep("Destination", 44))
names(newBart) <- c("Station", "Count", "Location")
ggplot(data = newBart, aes(x = Station, y = Count, fill = Location, color = Location, alpha = Location)) + geom_bar(stat = "identity", position = "identity") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
  scale_y_continuous(labels = scales::comma) + scale_colour_manual(values=c("lightblue4","red")) +
  scale_fill_manual(values=c("lightblue","pink")) +
  scale_alpha_manual(values=c(.3, .8))
```
